name: at_dude
description: A new project
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  at_app_flutter: ^5.0.0
  at_client_mobile: ^3.0.3
  at_contacts_flutter: ^4.0.1
  at_utils: ^3.0.0
  audioplayers: ^0.20.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.4.0
  google_fonts: ^2.3.1
  path_provider: ^2.0.5
  stop_watch_timer: ^1.3.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/audios/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dude_icon.png"



