name: at_dude
description: atDude App
version: 1.0.0

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  at_app_flutter: ^5.1.1
  at_backupkey_flutter: 4.0.7
  at_client_mobile: ^3.2.0
  at_contacts_flutter: ^4.0.5
  at_onboarding_flutter: ^6.0.0
  at_utils: ^3.0.9
  audioplayers: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^13.0.0
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  path_provider: ^2.0.5
  provider: ^6.0.2
  rive: ^0.10.1
  shared_preferences: ^2.0.15
  timezone: ^0.9.0
  url_launcher: ^6.1.8
  uuid: ^3.0.6


dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/nav_icons/
    - assets/images/personas/
    - assets/audios/
    - assets/animations/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dude_logo.png"
